gitRepoUrl = "https://github.com/ItsRune/VibezAPI"

[[classOrder]]
classes = ["VibezAPI", "Webhooks", "RateLimiter", "EmbedBuilder", "ActivityTracker"]

[[classOrder]]
section = "Ranker"
classes = ["Ranking", "Result"]

# Docusaurus settings
[docusaurus]
onBrokenLinks = "ignore"
onBrokenMarkdownLinks = "ignore"
favicon = "https://github.com/ItsRune/VibezAPI/blob/903c060edf6b7982f6c04bc68626f07c2a653255/.moonwave/static/favicon.png?raw=true"

# Home page settings
[home]
enabled = true
includeReadme = false

# Home page features
[[home.features]]
title = "Flexibility"
description = "VibezAPI is designed to be flexible and easy to use. It's designed to be used in any project, big or small."

[[home.features]]
title = "Easy to Use"
description = "Simplicity is key, and VibezAPI is no exception. It's designed to be easy to use, and easy to understand."

[[home.features]]
title = "Open Source"
description = "VibezAPI is open source, meaning you can contribute to it, and make it better for everyone."

# Navigation bar items
[navbar]
title = ""

[[navbar.items]]
href = "https://discord.gg/vdev"
label = "Discord"
position = "right"

[navbar.logo]
alt = "Vibez"
src = "https://github.com/ItsRune/VibezAPI/blob/10a41c5c42e209e883cab36f7f2c24d2489c4039/.moonwave/static/typography.png?raw=true"
width = 64
height = 64

# Footer
[footer]
style = "light"
copyright = "Copyright © 2024 ItsRune."

# Footer Documentation
[[footer.links]]
title = "Documentation"

[[footer.links.items]]
label = "Getting Started"
href = "/VibezAPI/docs/intro"

[[footer.links.items]]
label = "API Reference"
href = "/VibezAPI/api/VibezAPI"

# Footer Community
[[footer.links]]
title = "Community"

[[footer.links.items]]
label = "Roblox Group"
href = "https://www.roblox.com/groups/4604891/Vibez-Development#!/about"

[[footer.links.items]]
label = "Discord"
href = "https://discord.gg/vdev"

# Footer Other
[[footer.links]]
title = "Other"

[[footer.links.items]]
label = "Developer's Profile"
href = "https://www.roblox.com/users/107392833/profile"

[[footer.links.items]]
label = "Github"
href = "https://github.com/ItsRune/VibezAPI"