name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Aftman
      uses: ok-nick/setup-aftman@v0

    - name: Install Selene
      run: |
        curl -LO https://github.com/Kampfkarren/selene/archive/refs/tags/0.26.1.tar.gz
        tar xzf 0.26.1.tar.gz
        sudo mv selene-0.26.1 /usr/local/bin/

    - name: Lint
      run: |
        selene ./src