name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  style:
    name: Styling
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: JohnnyMorganz/stylua-action@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        version: v0.18.1
        args: --check ./src